# Generated by Django 5.0.11 on 2025-02-04 13:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="data_of_birth",
            new_name="date_of_birth",
        ),
    ]
